gggggggg

diff --git a/.github/workflows/callee.yml b/.github/workflows/callee.yml
--- a/.github/workflows/callee.yml
+++ b/.github/workflows/callee.yml
@@ -23,6 +23,7 @@ jobs:
             echo "success" > test-result
             exit 0
           else
+            sleep 10
             echo failure
             echo "failure" > test-result
             exit 1
@@ -33,23 +34,23 @@ jobs:
         with:
           name: shard-result-${{matrix.num}}
           path: test-result
-  after:
-    # continue-on-error: true
-    needs: ["shard-job"]
-    runs-on: ubuntu-22.04
-    if: ${{!cancelled()}}
-    steps:
-      - name: Download artifacts
-        uses: actions/download-artifact@v4
-        with:
-          pattern: shard-result-*
-          path: test-results/
-          # merge-multiple: true
-      - name: xxx
-        run: |
-          failures=$(cat test-results/**/* | grep -c failure)
-          echo $failures
-          if [ $failures -gt 0 ]; then
-            echo "::error::だめだった"
-            exit 1
-          fi
+  # after:
+  #   # continue-on-error: true
+  #   needs: ["shard-job"]
+  #   runs-on: ubuntu-22.04
+  #   if: ${{!cancelled()}}
+  #   steps:
+  #     - name: Download artifacts
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         pattern: shard-result-*
+  #         path: test-results/
+  #         # merge-multiple: true
+  #     - name: xxx
+  #       run: |
+  #         failures=$(cat test-results/**/* | grep -c failure)
+  #         echo $failures
+  #         if [ $failures -gt 0 ]; then
+  #           echo "::error::だめだった"
+  #           exit 1
+  #         fi
