a

diff --git a/.github/workflows/matrix-callee.yml b/.github/workflows/matrix-callee.yml
--- a/.github/workflows/matrix-callee.yml
+++ b/.github/workflows/matrix-callee.yml
@@ -34,10 +34,10 @@ jobs:
           echo "name $name"
           echo "sleep $sleep"
           echo "success $success"
-          sleep $sleep
-          if $success; then
-            echo "success"
-          else;
-            echo "::error::some error is occured"
-            exit 1
-          fi
+          #sleep $sleep
+          #if $success; then
+          #  echo "success"
+          #else;
+          #  echo "::error::some error is occured"
+          #  exit 1
+          #fi
